llm.build:
  name: sdktest-retry
  retries:
    max_retries: 1
  targets:
    download_file:
      environment_uri: space://environments/{{ space.variables.DEFAULT_CPU_ENVIRONMENT }}
      inputs:
        seed_data:
          uri: lh://staging/granite_dot_build.public/tables/maximo_digit_input1
      outputs:
        download_file:
          uri: lh://staging/granite_dot_build.public/tables/test_dl_step_data_{{ binding.path | short_hash }}
      steps:
        - step_uri: space://steps/download
          config:
            download_config:
              url1: https://huggingface.co/datasets/datasets-examples/doc-formats-jsonl-1/resolve/main/data.jsonl
              url2: https://huggingface.co/datasets/datasets-examples/doc-formats-jsonl-1/resolve/main/data.jsonl
              url3: https://huggingface.co/datasets/datasets-examples/doc-formats-jsonl-1/resolve/main/data.jsonl
              output_dir: /gb-read-write/downloads_{{ run_metadata.targetsteprun_id | short_hash }}
